- name: Deploy Apache and content on Rocky
  hosts: rocky
  become: yes
  tasks:
    - name: Install Apache web server
      dnf:
        name: httpd
        state: present

    - name: Upload default index.html for web server
      copy:
        src: /home/junhan/index.html
        dest: /var/www/html/index.html
        mode: "0644"

    - name: Create images directory if not exists
      file:
        path: /var/www/html/images
        state: directory
        mode: "0755"

    - name: Upload image to the web server
      copy:
        src: /home/junhan/images/two-rabbit.jpg
        dest: /var/www/html/images/two-rabbit.jpg
        mode: "0644"

    - name: Start Apache web server
      service:
        name: httpd
        state: started
        enabled: yes

- name: Install apache on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install apache web server
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Upload custom index.html to the web server
      copy:
        src: /home/junhan/index.html
        dest: /var/www/html/index.html
        mode: "0644"

    - name: Create images directory if it does not exist
      file:
        path: /var/www/html/images
        state: directory
        mode: "0755"

    - name: Upload image to the web server
      copy:
        src: /home/junhan/images/two-rabbit.jpg
        dest: /var/www/html/images/two-rabbit.jpg
        mode: "0644"

    - name: Start apache web server
      service:
        name: apache2
        state: started
        enabled: yes
