- name: Create known_hosts between server and nodes
  hosts: all
  connection: local # 대상 호스트에 연결하여 작업을 수행하지 않고, 로컬에서 명령을 실행
  serial: 1 # 한 번에 한 호스트씩 순차적으로 실행
  gather_facts: no
  
  tasks:
    - name: ssh-keyscan for known_hosts file
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }} # 매직변수는 앤서블에서 특별히 선언하지 않아도, 기본적으로 사용할 수 있는 변수들이 존재합니다. ansible_host를 호출하여 /etc/ansible/hosts에 있는 노드들의 값 중에 플레이북에서 호출한 노드들에 대한 정보를 자동으로 변수로 입력받을 것입니다.
      register: keyscan # 출력 결과를 keyscan 변수에 저장

    - name: input key
      lineinfile:      
        path: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes     
      with_items:
        - "{{ keyscan.stdout_lines }}" # 변수의 각 줄을 반복 처리하여, 각 키를 파일에 추가합니다.
